FROM node:20-alpine AS development
WORKDIR /app
RUN apk add --no-cache libc6-compat python3 make g++ postgresql16-client
COPY package*.json ./
COPY prisma/schema.prisma ./prisma/
RUN npm ci
COPY . .
RUN npx prisma generate
EXPOSE 4000 9229
CMD ["npm","run","start:dev"]
